services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: gamedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
