app:
  datasource:
    jdbc-url: "jdbc:mariadb://localhost:3316/gamedb_db"
    username: root
    password: mariadb
server:
  servlet.context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
    whitelabel.enabled: false
  port: 9191
  servlet.encoding.force: true
spring: # TODO Combine spring & app settings
  flyway:
    enabled: true
    validate-on-migrate: true
    user: root
    password: mariadb
    url: "jdbc:mariadb://localhost:3316/gamedb_db"
    baseline-on-migrate: true
  devtools.restart.enabled: true
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
