name: Lint
on: [push]
jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ESLint
        working-directory: ./web
        run: npm run lint
        
