name: "Lint"
on: ["push"]
jobs:
  lint-js:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        working-directory: ./web
        run: npm install
      - name: Run ESLint
        working-directory: ./web
        run: npm run lint:ci
  format-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v3
