name: "Lint"
on: [push]
jobs:
  lint-js:
    defaults:
      run:
        working-directory: ./web
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Run ESLint
        run: npm run lint:ci
  format-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v3
