name: Lint
on: [push]
jobs:
  lint-js:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        working-directory: ./web
        run: npm install
      - name: Run ESLint
        working-directory: ./web
        run: npm run lint:ci
        
