on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@main"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6.6"
        id: "todo"
        with:
          AUTO_ASSIGN: "StruckCroissant"
          IGNORE: "GAME-DB/web/src/styles/bootstrap-5.2.0-beta1-dist/js/"
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"

  
