name: TODO to Issue
  # You may pin to the exact commit or the version.
  # uses: alstr/todo-to-issue-action@2b1af285f4b0bfd0def9cc244b38b97ca780c60a
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@main"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6.6"
        id: "todo"
        with:
          AUTO_ASSIGN: "StruckCroissant"
          IGNORE: "GAME-DB/web/src/styles/bootstrap-5.2.0-beta1-dist/js/"
