name: "Test"
on: [push]
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm run test:e2e
